### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by kingsleyh** [mint-lang/example-todo#1]
Hi 

I cloned this and then ran `mint install then mint start` but when I navigate to `http://localhost:3000` I get an error:

<img width="1161" alt="screen shot 2018-06-09 at 18 56 11" src="https://user-images.githubusercontent.com/103770/41194651-ea57df30-6c16-11e8-8cdd-4daa0f97524a.png">

**Comment by gdotdesign** [comment]
Hey, thanks for creating this issue :+1: 

I need to add a readme to this project :sweat_smile: the error is because dependencies are not installed, you can install them with `mint install`.

I'll open up an issue about this in the main repository to figure out how to handle this with a nice error message.

**Comment by gdotdesign** [comment]
Oh sorry this is not that :sweat_smile: I needed to update to work with the latest version of Mint.

If you try it with the latest master it should work.

**Comment by kingsleyh** [comment]
Great thanks - I posted the initial error but I figured out it was due to missing dependencies - and then replaced it with the current error.

Great project - I love it :)
